"""Add 5-stage pipeline fields to Package model

Revision ID: 206456dfa91c
Revises: 58a5474078fe
Create Date: 2025-06-25 11:13:35.037916

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "206456dfa91c"
down_revision: Union[str, Sequence[str], None] = "58a5474078fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
