"""Add current_step and progress_pct to Package model

Revision ID: 58a5474078fe
Revises: 66860602041e
Create Date: 2025-06-23 12:20:00.731750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58a5474078fe"
down_revision: Union[str, Sequence[str], None] = "66860602041e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "packages",
        sa.Column(
            "current_step",
            sa.String(length=50),
            nullable=False,
            server_default="upload",
        ),
    )
    op.add_column(
        "packages",
        sa.Column("progress_pct", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packages", "progress_pct")
    op.drop_column("packages", "current_step")
    # ### end Alembic commands ###
