"""Add executable_names to metadata

Revision ID: 88cc2c77fd7d
Revises: 206456dfa91c
Create Date: 2025-06-27 17:10:50.134570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88cc2c77fd7d"
down_revision: Union[str, Sequence[str], None] = "206456dfa91c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metadata", sa.Column("executable_names", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metadata", "executable_names")
    # ### end Alembic commands ###
